version: '3.4'

volumes:
  ethgoerlidnpdappnodeeth_data: {}
  
services:
  ethgoerli.dnp.dappnode.eth:
    build: ./build
    image: ethgoerli.public.dappnode.eth:0.0.1
    container_name: ethgoerli.public.dappnode.eth
    restart: always
    volumes:
      - ethgoerlidnpdappnodeeth_data:/root/.local/share/goerli.ethereum/
    ports:
      - "30304:30303"
      - "30304:30303/udp"